### PR TITLE
Add support to riscv64 architecture

### PR DESCRIPTION
**Pull request by carlosedp**
Bump libraries to be able to build on riscv64 architecture.

Also required bumping netns dependencies on https://github.com/genuinetools/netns/pull/21

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @carlosedp did you not update Gopkg.toml?

**Comment by alexellis** [comment]
Re: netns, I'm not sure that @jessfraz is maintaining the project anymore. @crosbymichael offered to help convert over to go-cni :pray: - that would remove this dependency too. 

@carlosedp as far as you know, does go-cni work on RISCV from when you ported K8s over?

**Comment by carlosedp** [comment]
> Hi @carlosedp did you not update Gopkg.toml?

I've ran `dep ensure -update golang.org/x/sys` and it didn't update that file.

All CNI plugins build fine on Risc-V from source. Containerd also builds with CNI interface and Podman runs fine with the CNI plugins from (https://github.com/containernetworking/plugins).

**Comment by alexellis** [comment]
Good to hear CNI works fine. Now I need to do the work to move off netns or someone needs to do a PR for it. I have a sample project showing how to use CNI with containerd

**Comment by carlosedp** [comment]
I'd love to take a look and see if I can do it... if you could point me into the right direction :)

**Comment by alexellis** [comment]
See how I'm using weave and netns in a prerun hook? This example shows what we'd do instead of that.

https://github.com/alexellis/ctrofb/blob/master/cmd/network.go

**Comment by carlosedp** [comment]
Closing as this was addressed by PR #18.

**Pull request closed without merging**
